apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rails-assets-demo-prod
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: rails-assets-demo-prod
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: ruby
  - name: clusterBuilder
    value: full-jammy
  serviceClaims:
   - name: postgresql-2
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: postgresql-2
  env:
   - name: SECRET_KEY_BASE
     valueFrom:
       secretKeyRef:
         name: rails-secret-key-trev-cluster
         key: SECRET_KEY_BASE
  source:
    git:      
      url: https://github.com/trevorputbrese/rails-assets
      ref:
        branch: main