apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rails-asset-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: rails-asset-demo
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: clusterBuilder
    value: full-jammy
  serviceClaims:
   - name: postgresql-1
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: postgresql-1
  env:
   - name: SECRET_KEY_BASE
     valueFrom:
       secretKeyRef:
         name: rails-asset-demo-secret-key
         key: SECRET_KEY_BASE
  source:
    git:      
      url: https://github.com/trevorputbrese/samples
      ref:
        branch: main
    subPath:  ruby/rails_assets
